# Generated by Django 2.0.5 on 2018-06-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
