# Generated by Django 2.0.5 on 2018-06-01 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20180601_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='crest',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
